//go:build windows

package main

import (
    "archive/zip"
    "bytes"
    "embed"
    "fmt"
    "io"
    "os"
    "os/exec"
    "path/filepath"
    "runtime"
    "strings"
    "syscall"
    "time"
    "unsafe"
)

// payload.zip is generated by the release pipeline and MUST contain a prebuilt
// MiningVolume2023.bundle. The end-user machine never compiles C# source.
//go:embed payload.zip
var payloadFS embed.FS

const (
    productName = "MiningVolume HS-Next for AutoCAD 2023"
    version = "0.10.4"
    uninstallKey = `HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\MiningVolume2023`
)

func main() {
    if runtime.GOOS != "windows" { return }
    args := os.Args[1:]
    if hasArg(args, "--uninstall") {
        if !isAdmin() { elevate("--uninstall --elevated"); return }
        uninstall(); return
    }
    if !isAdmin() { elevate("--elevated"); return }
    install()
}

func install() {
    if processRunning("acad.exe") {
        msg("Hãy đóng toàn bộ AutoCAD 2023 trước khi cài MiningVolume.", 0x10); return
    }
    cad, err := findAutoCAD2023()
    if err != nil { msg(err.Error(), 0x10); return }

    temp := filepath.Join(os.TempDir(), fmt.Sprintf("MiningVolume_v0104_%d", os.Getpid()))
    os.RemoveAll(temp)
    if err := os.MkdirAll(temp, 0755); err != nil { msg(err.Error(), 0x10); return }
    defer os.RemoveAll(temp)
    if err := extractPayload(temp); err != nil { msg("Không giải nén được bộ cài: "+err.Error(), 0x10); return }

    source := filepath.Join(temp, "bundle", "MiningVolume2023.bundle")
    if err := validatePrebuiltBundle(source); err != nil {
        msg("Bộ cài không có binary Release hợp lệ. Không thay đổi AutoCAD.\n\n"+err.Error(), 0x10); return
    }

    programData := os.Getenv("ProgramData"); if programData == "" { programData = `C:\ProgramData` }
    appPlugins := filepath.Join(programData, "Autodesk", "ApplicationPlugins")
    target := filepath.Join(appPlugins, "MiningVolume2023.bundle")
    backup := target + ".v0104bak"
    os.MkdirAll(appPlugins, 0755)
    os.RemoveAll(backup)
    if exists(target) {
        if err := os.Rename(target, backup); err != nil { msg("Không sao lưu được bản cũ: "+err.Error(), 0x10); return }
    }
    if err := copyDir(source, target); err != nil {
        os.RemoveAll(target); restoreBackup(backup, target)
        msg("Không cài được bundle: "+err.Error(), 0x10); return
    }

    ok, detail := runAutoCADSelfTest(cad)
    if !ok {
        os.RemoveAll(target); restoreBackup(backup, target)
        writePersistentLog("selftest_failed", detail)
        msg("MiningVolume đã tự rollback vì kiểm thử trong AutoCAD 2023 không đạt.\n\n"+detail, 0x10); return
    }
    os.RemoveAll(backup)
    if err := registerUninstall(target); err != nil {
        msg("Add-in đã PASS trong AutoCAD nhưng chưa ghi được mục gỡ cài đặt: "+err.Error(), 0x30); return
    }
    msg("Cài đặt MiningVolume v0.10.4 thành công.\n\nAutoCAD 2023 runtime self-test: PASS.\nMáy không cần Visual Studio/Build Tools.\nMở AutoCAD: bảng MiningVolume sẽ tự hiện, kể cả khi Ribbon đang tắt.", 0x40)
}

func validatePrebuiltBundle(root string) error {
    required := []string{
        filepath.Join(root, "PackageContents.xml"),
        filepath.Join(root, "Contents", "Windows", "MiningVolume2023.dll"),
        filepath.Join(root, "Contents", "Windows", "MiningVolume.Core.dll"),
        filepath.Join(root, "Contents", "Windows", "MiningVolume.Surface.dll"),
        filepath.Join(root, "Contents", "Windows", "MiningVolume.Cad2023.dll"),
    }
    for _, p := range required { if !exists(p) { return fmt.Errorf("Thiếu file Release: %s", filepath.Base(p)) } }
    if exists(filepath.Join(root, "Contents", "Windows", "NetTopologySuite.dll")) {
        return fmt.Errorf("Release v0.10.4 không được phụ thuộc NetTopologySuite.dll")
    }
    return nil
}

func uninstall() {
    if processRunning("acad.exe") { msg("Hãy đóng AutoCAD trước khi gỡ MiningVolume.", 0x10); return }
    programData := os.Getenv("ProgramData"); if programData=="" { programData=`C:\ProgramData` }
    target := filepath.Join(programData,"Autodesk","ApplicationPlugins","MiningVolume2023.bundle")
    os.RemoveAll(target)
    exec.Command("reg","delete",uninstallKey,"/f").Run()
    msg("Đã gỡ MiningVolume khỏi AutoCAD.", 0x40)
}

func runAutoCADSelfTest(cad string) (bool, string) {
    acad := filepath.Join(cad, "acad.exe")
    if !exists(acad) { return false, "Không tìm thấy acad.exe" }
    log := filepath.Join(os.TempDir(), "MiningVolume_v0104_selftest.txt"); os.Remove(log)
    scr := filepath.Join(os.TempDir(), "MiningVolume_v0104_selftest.scr")
    os.WriteFile(scr, []byte("FILEDIA\r\n0\r\nCMDDIA\r\n0\r\nMVSELFTEST\r\n_.QUIT\r\n"), 0644)
    defer os.Remove(scr)

    cmd := exec.Command(acad, "/nologo", "/b", scr)
    cmd.Env = append(os.Environ(), "MININGVOLUME_SELFTEST_FILE="+log)
    if err := cmd.Start(); err != nil { return false, "Không mở được AutoCAD: "+err.Error() }
    deadline := time.Now().Add(150*time.Second)
    for time.Now().Before(deadline) {
        if b, err := os.ReadFile(log); err == nil {
            txt := string(b)
            if strings.Contains(txt, "Status=PASS") {
                done := make(chan error,1); go func(){done<-cmd.Wait()}()
                select { case <-done: case <-time.After(5*time.Second): _ = cmd.Process.Kill() }
                return true, txt
            }
            if strings.Contains(txt, "Status=FAIL") { _ = cmd.Process.Kill(); return false, txt }
        }
        time.Sleep(1*time.Second)
    }
    _ = cmd.Process.Kill(); return false, "Hết thời gian 150 giây nhưng không nhận được PASS từ MVSELFTEST."
}

func registerUninstall(bundlePath string) error {
    programData := os.Getenv("ProgramData"); if programData=="" { programData=`C:\ProgramData` }
    dir := filepath.Join(programData, "MiningVolume2023")
    if err := os.MkdirAll(dir,0755); err != nil { return err }
    exe, _ := os.Executable(); stored := filepath.Join(dir,"MiningVolume_Setup_v0.10.4.exe")
    if err := copyFile(exe,stored); err != nil { return err }
    vals := [][]string{
        {"/v","DisplayName","/t","REG_SZ","/d",productName,"/f"},
        {"/v","DisplayVersion","/t","REG_SZ","/d",version,"/f"},
        {"/v","Publisher","/t","REG_SZ","/d","MiningVolume Development","/f"},
        {"/v","InstallLocation","/t","REG_SZ","/d",bundlePath,"/f"},
        {"/v","UninstallString","/t","REG_SZ","/d","\""+stored+"\" --uninstall","/f"},
    }
    for _,v := range vals { a:=append([]string{"add",uninstallKey},v...); if err:=exec.Command("reg",a...).Run(); err!=nil{return err} }
    return nil
}

func findAutoCAD2023() (string,error) {
    candidates := []string{}
    if pf:=os.Getenv("ProgramFiles"); pf!="" { candidates=append(candidates,filepath.Join(pf,"Autodesk","AutoCAD 2023")) }
    candidates=append(candidates,`C:\Program Files\Autodesk\AutoCAD 2023`)
    for _,p:=range candidates { if exists(filepath.Join(p,"acad.exe")) && exists(filepath.Join(p,"AcMgd.dll")) { return p,nil } }
    out,_:=exec.Command("reg","query",`HKLM\SOFTWARE\Autodesk\AutoCAD\R24.2`,"/s","/v","AcadLocation").CombinedOutput()
    for _,line:=range strings.Split(string(out),"\n") {
        if !strings.Contains(line,"AcadLocation") { continue }
        parts:=strings.Fields(line); if len(parts)>=3 { p:=strings.Join(parts[2:]," "); if exists(filepath.Join(p,"acad.exe")){return p,nil} }
    }
    return "",fmt.Errorf("Không tìm thấy AutoCAD 2023 64-bit trên máy.")
}

func extractPayload(dst string) error {
    b,err:=payloadFS.ReadFile("payload.zip"); if err!=nil{return err}
    zr,err:=zip.NewReader(bytes.NewReader(b),int64(len(b))); if err!=nil{return err}
    for _,f:=range zr.File {
        clean:=filepath.Clean(f.Name); if strings.HasPrefix(clean,"..") { return fmt.Errorf("payload path không hợp lệ") }
        path:=filepath.Join(dst,clean)
        if f.FileInfo().IsDir(){ os.MkdirAll(path,0755); continue }
        if err:=os.MkdirAll(filepath.Dir(path),0755);err!=nil{return err}
        rc,err:=f.Open(); if err!=nil{return err}; w,err:=os.Create(path); if err!=nil{rc.Close();return err}
        _,e:=io.Copy(w,rc); w.Close(); rc.Close(); if e!=nil{return e}
    }
    return nil
}

func writePersistentLog(kind, content string) {
    pd:=os.Getenv("ProgramData"); if pd==""{pd=`C:\ProgramData`}
    dir:=filepath.Join(pd,"MiningVolume2023","Logs"); _=os.MkdirAll(dir,0755)
    _=os.WriteFile(filepath.Join(dir,kind+".txt"),[]byte(content),0644)
}
func copyDir(src,dst string) error { return filepath.Walk(src,func(path string,info os.FileInfo,err error) error{ if err!=nil{return err}; rel,_:=filepath.Rel(src,path); out:=filepath.Join(dst,rel); if info.IsDir(){return os.MkdirAll(out,0755)}; return copyFile(path,out) }) }
func copyFile(src,dst string) error { in,err:=os.Open(src);if err!=nil{return err};defer in.Close();os.MkdirAll(filepath.Dir(dst),0755);out,err:=os.Create(dst);if err!=nil{return err};_,e:=io.Copy(out,in);c:=out.Close();if e!=nil{return e};return c }
func restoreBackup(backup,target string){ if exists(backup){ _=os.Rename(backup,target) } }
func exists(p string) bool { _,e:=os.Stat(p);return e==nil }
func hasArg(args []string,s string) bool { for _,a:=range args{if strings.EqualFold(a,s){return true}};return false }
func processRunning(name string) bool { out,_:=exec.Command("tasklist","/FI","IMAGENAME eq "+name).CombinedOutput();return strings.Contains(strings.ToLower(string(out)),strings.ToLower(name)) }
func isAdmin() bool { return exec.Command("net","session").Run()==nil }
func elevate(extra string) { exe,_:=os.Executable(); ps:=fmt.Sprintf("Start-Process -FilePath %s -ArgumentList %s -Verb RunAs",psQuote(exe),psQuote(extra)); _=exec.Command("powershell.exe","-NoProfile","-WindowStyle","Hidden","-Command",ps).Start() }
func psQuote(s string) string { return "'"+strings.ReplaceAll(s,"'","''")+"'" }
func msg(text string, icon uintptr) { user32:=syscall.NewLazyDLL("user32.dll"); proc:=user32.NewProc("MessageBoxW"); t,_:=syscall.UTF16PtrFromString(text); c,_:=syscall.UTF16PtrFromString(productName); proc.Call(0,uintptr(unsafe.Pointer(t)),uintptr(unsafe.Pointer(c)),0x0|icon) }