//go:build windows

package main

import (
    "archive/zip"
    "bytes"
    "embed"
    "fmt"
    "io"
    "os"
    "os/exec"
    "path/filepath"
    "runtime"
    "strings"
    "syscall"
    "time"
    "unsafe"
)

// payload.zip is generated by the release pipeline and MUST contain a prebuilt
// MiningVolume2023.bundle. The end-user machine never compiles C# source.
//go:embed payload.zip
var payloadFS embed.FS

const (
    productName = "IMSAT MiningVolume HS-Next for AutoCAD 2023"
    version = "0.10.4"
    uninstallKey = `HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\MiningVolume2023`
)

func main() {
    if runtime.GOOS != "windows" { return }
    args := os.Args[1:]
    if hasArg(args, "--uninstall") {
        if !isAdmin() { elevate("--uninstall --elevated"); return }
        uninstall(); return
    }
    if !isAdmin() { elevate("--elevated"); return }
    install()
}

func install() {
    if processRunning("acad.exe") {
        msg("Hãy đóng toàn bộ AutoCAD 2023 trước khi cài MiningVolume.", 0x10); return
    }
    cad, err := findAutoCAD2023()
    if err != nil { msg(err.Error(), 0x10); return }

    temp := filepath.Join(os.TempDir(), fmt.Sprintf("MiningVolume_v0104_%d", os.Getpid()))
    os.RemoveAll(temp)
    if err := os.MkdirAll(temp, 0755); err != nil { msg(err.Error(), 0x10); return }
    defer os.RemoveAll(temp)
    if err := extractPayload(temp); err != nil { msg("Không giải nén được bộ cài: "+err.Error(), 0x10); return }

    source := filepath.Join(temp, "bundle", "MiningVolume2023.bundle")
    if err := validatePrebuiltBundle(source); err != nil {
        msg("Bộ cài không có binary Release hợp lệ. Không thay đổi AutoCAD.\n\n"+err.Error(), 0x10); return
    }

    programData := os.Getenv("ProgramData"); if programData == "" { programData = `C:\ProgramData` }
    appPlugins := filepath.Join(programData, "Autodesk", "ApplicationPlugins")
    target := filepath.Join(appPlugins, "MiningVolume2023.bundle")
    backup := target + ".v0104bak"
    os.MkdirAll(appPlugins, 0755)

    // Recover conservatively from an interrupted previous install before starting
    // a new transaction. An unverified target is never preferred over its backup.
    if exists(backup) {
        os.RemoveAll(target)
        if err := restoreBackup(backup, target); err != nil {
            msg("Không khôi phục được bản sao lưu từ lần cài trước: "+err.Error(), 0x10); return
        }
    }
    if exists(target) {
        if err := os.Rename(target, backup); err != nil { msg("Không sao lưu được bản cũ: "+err.Error(), 0x10); return }
    }
    if err := copyDir(source, target); err != nil {
        os.RemoveAll(target); _ = restoreBackup(backup, target)
        msg("Không cài được bundle: "+err.Error(), 0x10); return
    }

    // Runtime verification is a release-pipeline responsibility. The end-user
    // installer must never launch AutoCAD automatically or expose development
    // self-test behavior. A RUNTIME-PASS artifact has already been verified on
    // a real AutoCAD 2023 runner before this Setup is published.
    os.RemoveAll(backup)
    if err := registerUninstall(target, cad); err != nil {
        msg("MiningVolume đã được chép vào AutoCAD nhưng chưa ghi được mục gỡ cài đặt: "+err.Error(), 0x30); return
    }
    writePersistentLog("install", "Status=INSTALLED\r\nAutoCAD="+filepath.Join(cad,"acad.exe"))
    msg("Cài đặt IMSAT MiningVolume v0.10.4 thành công.\n\nSetup không tự mở AutoCAD.\nMáy không cần Visual Studio/Build Tools.\nKhi cần sử dụng, hãy mở AutoCAD 2023 rồi dùng Ribbon MINING VOLUME, Menu Bar MINING VOLUME hoặc lệnh TKL.\nBảng MiningVolume không tự mở theo mặc định.", 0x40)
}

func validatePrebuiltBundle(root string) error {
    packageXml := filepath.Join(root, "PackageContents.xml")
    windowsDir := filepath.Join(root, "Contents", "Windows")
    allowedDll := map[string]bool{
        "miningvolume2023.dll": true,
        "miningvolume.core.dll": true,
        "miningvolume.surface.dll": true,
        "miningvolume.cad2023.dll": true,
    }

    required := []string{
        packageXml,
        filepath.Join(windowsDir, "MiningVolume2023.dll"),
        filepath.Join(windowsDir, "MiningVolume.Core.dll"),
        filepath.Join(windowsDir, "MiningVolume.Surface.dll"),
        filepath.Join(windowsDir, "MiningVolume.Cad2023.dll"),
    }
    for _, p := range required {
        if !exists(p) { return fmt.Errorf("Thiếu file Release: %s", filepath.Base(p)) }
    }

    entries, err := os.ReadDir(windowsDir)
    if err != nil { return fmt.Errorf("Không đọc được thư mục binary Release: %w", err) }
    for _, entry := range entries {
        if entry.IsDir() || !strings.EqualFold(filepath.Ext(entry.Name()), ".dll") { continue }
        if !allowedDll[strings.ToLower(entry.Name())] {
            return fmt.Errorf("Bundle chứa DLL ngoài danh sách cho phép: %s", entry.Name())
        }
    }

    xmlBytes, err := os.ReadFile(packageXml)
    if err != nil { return fmt.Errorf("Không đọc được PackageContents.xml: %w", err) }
    xmlText := string(xmlBytes)
    for _, token := range []string{
        `AppVersion="0.10.4"`,
        `SeriesMin="R24.2"`,
        `SeriesMax="R24.2"`,
        `LoadOnAutoCADStartup="True"`,
    } {
        if !strings.Contains(xmlText, token) {
            return fmt.Errorf("PackageContents.xml thiếu cấu hình bắt buộc: %s", token)
        }
    }
    return nil
}

func uninstall() {
    if processRunning("acad.exe") { msg("Hãy đóng AutoCAD trước khi gỡ MiningVolume.", 0x10); return }
    programData := os.Getenv("ProgramData"); if programData=="" { programData=`C:\ProgramData` }
    target := filepath.Join(programData,"Autodesk","ApplicationPlugins","MiningVolume2023.bundle")
    os.RemoveAll(target)
    os.Remove(filepath.Join(programData, "Microsoft", "Windows", "Start Menu", "Programs", "IMSAT MiningVolume.lnk"))
    exec.Command("reg","delete",uninstallKey,"/f").Run()
    msg("Đã gỡ MiningVolume khỏi AutoCAD.", 0x40)
}

func runAutoCADSelfTest(cad string) (bool, string) {
    acad := filepath.Join(cad, "acad.exe")
    if !exists(acad) { return false, "Không tìm thấy acad.exe" }
    log := filepath.Join(os.TempDir(), "MiningVolume_v0104_selftest.txt"); os.Remove(log)
    scr := filepath.Join(os.TempDir(), "MiningVolume_v0104_selftest.scr")
    os.WriteFile(scr, []byte("FILEDIA\r\n0\r\nCMDDIA\r\n0\r\nMVSELFTEST\r\n_.QUIT\r\n"), 0644)
    defer os.Remove(scr)

    cmd := exec.Command(acad, "/nologo", "/b", scr)
    cmd.Env = append(os.Environ(), "MININGVOLUME_SELFTEST_FILE="+log)
    if err := cmd.Start(); err != nil { return false, "Không mở được AutoCAD: "+err.Error() }
    deadline := time.Now().Add(150*time.Second)
    for time.Now().Before(deadline) {
        if b, err := os.ReadFile(log); err == nil {
            txt := string(b)
            if strings.Contains(txt, "Status=PASS") {
                if !strings.Contains(txt, "MiningVolume HS-Next v0.10.4 runtime self-test") {
                    _ = cmd.Process.Kill()
                    return false, "MVSELFTEST trả PASS nhưng log không đúng phiên bản v0.10.4.\n\n"+txt
                }
                required := []string{
                    "PASS | Khởi tạo đầy đủ giao diện MiningVolume",
                    "PASS | Bật/tắt palette MiningVolume hoạt động",
                    "PASS | AutoCAD tạo/ghi/đếm đúng layer TIN hiện trạng",
                    "PASS | AutoCAD tạo/ghi/đếm đúng layer TIN thiết kế",
                    "PASS | Layer TIN đúng màu quy ước: hiện trạng ACI 1, thiết kế ACI 3",
                    "PASS | Layer TIN chỉ chứa 3DFACE và được khóa sau khi ghi",
                    "PASS | Có thể ẩn cả hai TIN và layer vẫn khóa",
                    "PASS | Có thể hiện lại cả hai TIN và layer vẫn khóa",
                }
                for _, token := range required {
                    if !strings.Contains(txt, token) {
                        _ = cmd.Process.Kill()
                        return false, "MVSELFTEST thiếu kiểm tra runtime bắt buộc: "+token+"\n\n"+txt
                    }
                }
                done := make(chan error,1); go func(){done<-cmd.Wait()}()
                select { case <-done: case <-time.After(5*time.Second): _ = cmd.Process.Kill() }
                return true, txt
            }
            if strings.Contains(txt, "Status=FAIL") { _ = cmd.Process.Kill(); return false, txt }
        }
        time.Sleep(1*time.Second)
    }
    _ = cmd.Process.Kill(); return false, "Hết thời gian 150 giây nhưng không nhận được PASS từ MVSELFTEST."
}

func registerUninstall(bundlePath, cadDir string) error {
    programData := os.Getenv("ProgramData"); if programData=="" { programData=`C:\ProgramData` }
    dir := filepath.Join(programData, "MiningVolume2023")
    if err := os.MkdirAll(dir,0755); err != nil { return err }
    exe, _ := os.Executable(); stored := filepath.Join(dir,"MiningVolume_Setup_v0.10.4.exe")
    if err := copyFile(exe,stored); err != nil { return err }
    vals := [][]string{
        {"/v","DisplayName","/t","REG_SZ","/d",productName,"/f"},
        {"/v","DisplayVersion","/t","REG_SZ","/d",version,"/f"},
        {"/v","Publisher","/t","REG_SZ","/d","Viện Khoa học Công nghệ Mỏ - Vinacomin","/f"},
        {"/v","InstallLocation","/t","REG_SZ","/d",bundlePath,"/f"},
        {"/v","DisplayIcon","/t","REG_SZ","/d",stored+",0","/f"},
        {"/v","UninstallString","/t","REG_SZ","/d","\""+stored+"\" --uninstall","/f"},
    }
    for _,v := range vals { a:=append([]string{"add",uninstallKey},v...); if err:=exec.Command("reg",a...).Run(); err!=nil{return err} }
    if err := createStartMenuShortcut(cadDir, stored); err != nil { return err }
    return nil
}

func createStartMenuShortcut(cadDir, iconExe string) error {
    programData := os.Getenv("ProgramData"); if programData=="" { programData=`C:\ProgramData` }
    menuDir := filepath.Join(programData, "Microsoft", "Windows", "Start Menu", "Programs")
    if err := os.MkdirAll(menuDir, 0755); err != nil { return err }
    shortcut := filepath.Join(menuDir, "IMSAT MiningVolume.lnk")
    target := filepath.Join(cadDir, "acad.exe")
    ps := "$s=(New-Object -ComObject WScript.Shell).CreateShortcut(" + psQuote(shortcut) + ");" +
        "$s.TargetPath=" + psQuote(target) + ";" +
        "$s.WorkingDirectory=" + psQuote(cadDir) + ";" +
        "$s.Description='IMSAT MiningVolume - Mine Survey & Earthwork';" +
        "$s.IconLocation=" + psQuote(iconExe + ",0") + ";" +
        "$s.Save()"
    return exec.Command("powershell.exe","-NoProfile","-WindowStyle","Hidden","-Command",ps).Run()
}

func findAutoCAD2023() (string,error) {
    candidates := []string{}
    if pf:=os.Getenv("ProgramFiles"); pf!="" { candidates=append(candidates,filepath.Join(pf,"Autodesk","AutoCAD 2023")) }
    candidates=append(candidates,`C:\Program Files\Autodesk\AutoCAD 2023`)
    for _,p:=range candidates { if exists(filepath.Join(p,"acad.exe")) && exists(filepath.Join(p,"AcMgd.dll")) { return p,nil } }
    out,_:=exec.Command("reg","query",`HKLM\SOFTWARE\Autodesk\AutoCAD\R24.2`,"/s","/v","AcadLocation").CombinedOutput()
    for _,line:=range strings.Split(string(out),"\n") {
        if !strings.Contains(line,"AcadLocation") { continue }
        parts:=strings.Fields(line); if len(parts)>=3 { p:=strings.Join(parts[2:]," "); if exists(filepath.Join(p,"acad.exe")){return p,nil} }
    }
    return "",fmt.Errorf("Không tìm thấy AutoCAD 2023 64-bit trên máy.")
}

func extractPayload(dst string) error {
    b,err:=payloadFS.ReadFile("payload.zip"); if err!=nil{return err}
    zr,err:=zip.NewReader(bytes.NewReader(b),int64(len(b))); if err!=nil{return err}
    for _,f:=range zr.File {
        clean:=filepath.Clean(f.Name); if strings.HasPrefix(clean,"..") { return fmt.Errorf("payload path không hợp lệ") }
        path:=filepath.Join(dst,clean)
        if f.FileInfo().IsDir(){ os.MkdirAll(path,0755); continue }
        if err:=os.MkdirAll(filepath.Dir(path),0755);err!=nil{return err}
        rc,err:=f.Open(); if err!=nil{return err}; w,err:=os.Create(path); if err!=nil{rc.Close();return err}
        _,e:=io.Copy(w,rc); w.Close(); rc.Close(); if e!=nil{return e}
    }
    return nil
}

func writeRuntimeVerification(cadDir, selfTest string) {
    pd:=os.Getenv("ProgramData"); if pd==""{pd=`C:\ProgramData`}
    dir:=filepath.Join(pd,"MiningVolume2023","Logs"); _=os.MkdirAll(dir,0755)
    content:=fmt.Sprintf(
        "MiningVolume HS-Next v0.10.4 runtime verification\r\n"+
        "Timestamp=%s\r\nStatus=PASS\r\nAutoCAD=%s\r\n\r\n%s",
        time.Now().Format(time.RFC3339), filepath.Join(cadDir,"acad.exe"), selfTest)
    _=os.WriteFile(filepath.Join(dir,"runtime_verification.txt"),[]byte(content),0644)
}

func writePersistentLog(kind, content string) {
    pd:=os.Getenv("ProgramData"); if pd==""{pd=`C:\ProgramData`}
    dir:=filepath.Join(pd,"MiningVolume2023","Logs"); _=os.MkdirAll(dir,0755)
    _=os.WriteFile(filepath.Join(dir,kind+".txt"),[]byte(content),0644)
}
func copyDir(src,dst string) error { return filepath.Walk(src,func(path string,info os.FileInfo,err error) error{ if err!=nil{return err}; rel,_:=filepath.Rel(src,path); out:=filepath.Join(dst,rel); if info.IsDir(){return os.MkdirAll(out,0755)}; return copyFile(path,out) }) }
func copyFile(src,dst string) error { in,err:=os.Open(src);if err!=nil{return err};defer in.Close();os.MkdirAll(filepath.Dir(dst),0755);out,err:=os.Create(dst);if err!=nil{return err};_,e:=io.Copy(out,in);c:=out.Close();if e!=nil{return e};return c }
func restoreBackup(backup,target string) error {
    if !exists(backup) { return nil }
    os.RemoveAll(target)
    return os.Rename(backup,target)
}
func exists(p string) bool { _,e:=os.Stat(p);return e==nil }
func hasArg(args []string,s string) bool { for _,a:=range args{if strings.EqualFold(a,s){return true}};return false }
func processRunning(name string) bool { out,_:=exec.Command("tasklist","/FI","IMAGENAME eq "+name).CombinedOutput();return strings.Contains(strings.ToLower(string(out)),strings.ToLower(name)) }
func isAdmin() bool { return exec.Command("fltmc").Run()==nil }
func elevate(extra string) { exe,_:=os.Executable(); ps:=fmt.Sprintf("Start-Process -FilePath %s -ArgumentList %s -Verb RunAs",psQuote(exe),psQuote(extra)); _=exec.Command("powershell.exe","-NoProfile","-WindowStyle","Hidden","-Command",ps).Start() }
func psQuote(s string) string { return "'"+strings.ReplaceAll(s,"'","''")+"'" }
func msg(text string, icon uintptr) { user32:=syscall.NewLazyDLL("user32.dll"); proc:=user32.NewProc("MessageBoxW"); t,_:=syscall.UTF16PtrFromString(text); c,_:=syscall.UTF16PtrFromString(productName); proc.Call(0,uintptr(unsafe.Pointer(t)),uintptr(unsafe.Pointer(c)),0x0|icon) }